# This workflow will install backend's requirements and run tests

name: Take Screenshot

on:
  push:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Download Thunderbird
      run: wget https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/115.11.1/linux-x86_64/en-CA/thunderbird-115.11.1.tar.bz2

    - name: Untar Thunderbird
      run: mkdir ./tb && tar -xf thunderbird-115.11.1.tar.bz2 -C ./tb

    - name: Allow exec
      run: chmod +x ./tb/thunderbird/thunderbird-bin

    - name: Install reqs
      run: pip install -r ./requirements.lock

    - name: Run Thunderbird
      run: ./tb/thunderbird/thunderbird-bin --headless --marionette &

    - name: Run Screenshot Script
      run: python src/marionette/main.py

    - uses: actions/upload-artifact@v4
      with:
        name: screenshot.png
        path: ./out.png