# This workflow will install backend's requirements and run tests

name: Take Screenshot

on:
  push:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies

    - name: Download Thunderbird
      run: wget https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/128.1.0esr/linux-x86_64/en-CA/thunderbird-128.1.0esr.tar.bz2

    - name: Untar Thunderbird
      run: mkdir ./tb && tar -xf thunderbird-128.1.0esr.tar.bz2 -C ./tb

    - name: Allow exec
      run: chmod +x ./tb/thunderbird/thunderbird-bin

    - name: Install reqs
      run: pip install -r ./requirements.lock

    #- name: Run local imap
    #  run: docker run --name smtp4dev -d -p 5000:80 -p 2525:25 -p 143:143 rnwood/smtp4dev

    - name: Run Screenshot Script
      run: M_THUNDERBIRD_PROFILE=./profiles/website M_THUNDERBIRD_BIN=./tb/thunderbird/thunderbird-bin python src/marionette/main.py

    #- name: Stop local imap
    #  run: docker stop smtp4dev

    - uses: actions/upload-artifact@v4
      with:
        name: mail-screen.png
        path: ./mail-screen.png

    - uses: actions/upload-artifact@v4
      with:
        name: calendar-screen.png
        path: ./calendar-screen.png

    - uses: actions/upload-artifact@v4
      with:
        name: gecko.log
        path: ./gecko.log